### ISSUE TITLE
Bug when using shapes tool.

### ISSUE THREAD

**Issue by LinuxBeaver** [lbalazscs/Pixelitor#209] opened 2021-07-06 03:34 UTC
I forgot what I did but this bug happened. 

![image](https://user-images.githubusercontent.com/78667207/124538394-17309b00-de0b-11eb-90c9-8d22aab5d4e7.png)

Program Error
 

Message:
    java.lang.NullPointerException: Cannot invoke "pixelitor.tools.util.ImDrag.transformedCopy(java.awt.geom.AffineTransform)" because "this.origImDrag" is null
Level:
    SEVERE
Stack Trace:
Cannot invoke "pixelitor.tools.util.ImDrag.transformedCopy(java.awt.geom.AffineTransform)" because "this.origImDrag" is null
    pixelitor.tools.shapes.StyledShape.transform(StyledShape.java:243)
    pixelitor.tools.transform.TransformBox.applyTransform(TransformBox.java:260)
    pixelitor.tools.transform.TransformBox.cornerHandlesMoved(TransformBox.java:244)
    pixelitor.tools.transform.TransformBox.transform(TransformBox.java:171)
    pixelitor.tools.transform.RotationHandle.mouseDragged(RotationHandle.java:72)
    pixelitor.tools.transform.TransformBox.processMouseDragged(TransformBox.java:350)
    pixelitor.tools.shapes.ShapesTool.ongoingDrag(ShapesTool.java:296)
    pixelitor.tools.DragTool.mouseDragged(DragTool.java:86)
    pixelitor.tools.toolhandlers.CurrentToolHandler.mouseDragged(CurrentToolHandler.java:43)
    pixelitor.tools.toolhandlers.ToolHandler.handleMouseDragged(ToolHandler.java:49)
    pixelitor.tools.toolhandlers.ToolHandler.handleMouseDragged(ToolHandler.java:52)
    pixelitor.tools.toolhandlers.ToolHandler.handleMouseDragged(ToolHandler.java:52)
    pixelitor.tools.toolhandlers.ToolHandlerChain.handleMouseDragged(ToolHandlerChain.java:94)
    pixelitor.tools.Tools$EventDispatcher.mouseDragged(Tools.java:233)
    pixelitor.gui.View.mouseDragged(View.java:211)
    java.desktop/java.awt.Component.processMouseMotionEvent(Component.java:6665)
    java.desktop/javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3360)
    java.desktop/java.awt.Component.processEvent(Component.java:6386)
    java.desktop/java.awt.Container.processEvent(Container.java:2264)
    java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
    java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
    java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
    java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
    java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4580)
    java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
    java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
    java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
    java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
    java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
    java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
    java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
    java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
    java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
    java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
    java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
    java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
    java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by lbalazscs** [comment] 2021-07-06 18:33
Thank you for reporting it! I could reproduce the error based on the stack trace (or at least I found one way to reproduce it). The fix is in github, and it should be in the beta 5, which will be released within a few days.

**Comment by LinuxBeaver** [comment] 2021-07-10 05:43
Awesome, also nice work adding the Print option. (even though I don't use printers ever). I hope Pixelitor 4.30/4.3X is released soon.

**Comment by lbalazscs** [comment] 2021-07-10 11:41
I also don't have a printer because I don't like them, so I tested this only by printing into a file... That should be enough, because if it works, it means that Pixelitor successfully sent the printing information to the operating system. Could be a way of creating PDF files with custom margins, even if you never print them.

**Comment by lbalazscs** [comment] 2022-04-14 22:58
The fix is included in the final 4.3.0, which was just released.

**Closed by lbalazscs** 2022-04-14 22:58 UTC
Labels: bug
