### ISSUE TITLE
Program freeze when zooming in over 1100% with Pixel Grid on

### ISSUE THREAD

**Issue by Imerion** [lbalazscs/Pixelitor#140] opened 2020-10-30 00:04 UTC
I just tried the dev version 4.2.4 to test various features. Most things seem to work perfectly, but I noticed one oddity: There is a freeze of about 5-10 seconds when I zoom in over 1100% with Pixel Grid on. I believe this might be a bug of some kind since it doesn't happen when I zoom in without Pixel Grid on. After the wait the pixel grid does appear, but the program is too slow to use until I zoom out. My computer is from 2018 and quite fast, so that is probably not the reason.

**Comment by lbalazscs** [comment] 2020-10-30 01:42
Thank you for reporting this. Sadly the fix for this bug will be probably the disabling of the "Pixel Grid" feature on Linux. 

When I first implemented "Pixel Grid" (on Windows), I was very happy with it until I noticed that if I have both "Pixel Grid" and a selection, then everything becomes very slow. I spent quite some time with this problem, but as far as I understand, the problem is not in my code, but in the Java graphical libraries. So I decided to show a pixel grid only if there is no selection. 

Later I actually discovered that on Linux (running on a virtual machine on top of Windows) things are even worse: the slowdown appears even without selections (as you described), but I convinced myself that this might be caused by the virtual machine. Now it turns out that the virtual machine was innocent... (I assume that you are running Linux directly on the hardware)

So this is the reason why I will probably disable the feature instead of fixing it. If you find other bugs, please keep reporting them, 99% of them are fixable...

**Comment by Imerion** [comment] 2020-10-30 10:22
I see! I am indeed running native Linux, but I can live without the Pixel Grid. I actually do pixel-graphics for my games without it, so its no problem. Now I was just clicking around to bugtest things. :) I will tell you if I find anything else. Perhaps the feature can be brought back in the future if the Java libraries get upgraded.

**Closed** 2020-11-01 06:32 UTC
Labels: bug

**Comment by lbalazscs** [comment] 2020-11-02 21:22
Fixed in GitHub (by disabling "Pixel Grid" on Linux).

**Comment by lbalazscs** [comment] 2021-02-11 18:41
In the current version the pixel grid is enabled again on Linux, and it's also enabled when there is a selection. See issue #153

**Comment by Imerion** [comment] 2021-02-12 00:40
That is really good news! Awesome!
