### ISSUE TITLE
Tools from the toolbar do not work after use of keyboard shortcuts «Alt + space»

### ISSUE THREAD

**Issue by ShirabK** [lbalazscs/Pixelitor#45] opened 2019-09-06 14:53 UTC
After starting the application and pressing the key combination “Alt + Space”, work with the toolbar becomes inactive. Only restarting the application solves the problem.
**Steps to  reproduce:**
1) Run the application
2) Open a file of any extension
3) Press the keyboard shortcut "Alt + Space"
4) Close the popup menu
5) Select any tool from the toolbar
6) Take an action to edit the image
Result: Nothing happens when you try to edit the image.
Expected Result: Image editing works.
Restarting the application solves the problem.

Test environment: Windows 10 Home 64-bit, Pixelitor 4.2.0, Java Version 8.

**Comment by lbalazscs** [comment] 2019-09-06 15:01
I am closing this, because it is a duplicate of #29

**Closed by lbalazscs** 2019-09-06 15:01 UTC
