### ISSUE TITLE
Bug in displaying strikethrough and underline text when glow effects are enabled

### ISSUE THREAD

**Issue by kr1zo** [lbalazscs/Pixelitor#65] opened 2019-09-27 02:31 UTC
**Pixelitor version:** 4.2.1
**Java version:** 1.8.0_221
**OS:** Windows 10 x64

**Severity:** S3 Major
**Priority:** P2 Medium
**Component:** VISUAL

**Summary:**
Bug in displaying strikethrough and underline text when glow effects are enabled. Strikethrough and underline lines are in the background and are not visible enough with certain glow settings.

**Steps to reproduce:**
1. Run the Pixelitor.
2. Create a new image (Ctrl + N).
3. Open the interface for adding and editing text (Filter -> Text...).
4. Add text and enable the effects of Glow, Inner Glow, Neon Border, Drop Shadow.
5. Open advanced text settings (Advanced...).
6. Add to text Strikethrough and Underline.

**Expected result:**
Strikethrough and Underline should not be in background.

**Link (screenshots/video):**
https://yadi.sk/i/-TyQ2xsZS2Dktw

**Comment by lbalazscs** [comment] 2019-09-29 17:54
Thank you for reporting it, but I am closing this because it is caused by the same problem as issue #64 
The fix for #64 also fixed this

**Closed by lbalazscs** 2019-09-29 17:54 UTC
Labels: duplicate
