### ISSUE TITLE
The undo function when editing an image cancels only 5 actions

### ISSUE THREAD

**Issue by AlexHromi** [lbalazscs/Pixelitor#48] opened 2019-09-18 15:09 UTC
Reproducibility: always
Severity: Significant
Priority: High
Software:
Pixelator 4.2.0
Windows 10 64 bit
Java Version 1.8.0_201
Description:

The features of the application indicate unlimited cancellation of the changes. The undo tool cancels only 5 actions

Playback Actions:

1. Create a new image
2. Select Crop Tools
3. Draw 6 lines
4. Press "CTRL + Z" 6 times

Expected Result:

Cancel all changes

The result obtained:

Cancel only 5 actions

**Comment by lbalazscs** [comment] 2019-09-18 15:30
Thank you for reporting it, but this is a misunderstanding: the app has unlimited undo/redo only in the sense that in Edit/Preferences you can set any number of undo/redo levels. The default is not higher because storing the undo information increases your memory usage and the chances of running out of memory.

Perhaps I should reformulate the description of the app (suggestions are welcome!), but I am closing this issue, because it is not a bug.

**Closed by lbalazscs** 2019-09-18 15:30 UTC

**Comment by AlexHromi** [comment] 2019-09-18 17:03
> Thank you for reporting it, but this is a misunderstanding: the app has unlimited undo/redo only in the sense that in Edit/Preferences you can set any number of undo/redo levels. The default is not higher because storing the undo information increases your memory usage and the chances of running out of memory.
> 
> Perhaps I should reformulate the description of the app (suggestions are welcome!), but I am closing this issue, because it is not a bug.

Oh, sorry, not a very clear decision to implement this system if it weren’t for your message, I would randomly poke all the buttons)
