### ISSUE TITLE
Program error when opening GIF with transparent background 

### ISSUE THREAD

**Issue by fisheye123** [lbalazscs/Pixelitor#40] opened 2019-09-04 14:22 UTC
**Severity**: Minor
**Priority**: Medium
**Reproducibility**: Always
**Environment**: Pixelitor 4.2.0, Windows 10 x64, Java 1.8.0_221
**Steps to reproduce**:
	1) Run the Pixelitor
	2) Click on the tab "File" and select "Open" in the drop-down list
	3) In the window that opens, find the path to the image with a transparent background and select it
	4) Press the button "Open"
**Actual result**: Program error message appeared
`
Message:
    java.lang.ArrayIndexOutOfBoundsException: 4096
Level:
    SEVERE
Stack Trace:
4096
    com.sun.imageio.plugins.gif.GIFImageReader.read(Unknown Source)
    pixelitor.io.TrackedIO.readFromIIS(TrackedIO.java:136)
    pixelitor.io.TrackedIO.read(TrackedIO.java:105)
    pixelitor.io.TrackedIO.uncheckedRead(TrackedIO.java:93)
    pixelitor.io.OpenSave.lambda$loadSimpleFile$1(OpenSave.java:84)
    java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
    java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    java.lang.Thread.run(Unknown Source)`
**Expected result**: The message about format is incorrect

**Comment by lbalazscs** [comment] 2019-09-04 15:10
I could not reproduce it with the transparent-background gifs I tried. Please attach your file to this issue. Here's how: https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests

**Comment by fisheye123** [comment] 2019-09-04 15:24
![catTranparentGIF](https://user-images.githubusercontent.com/17645129/64268701-c592fd00-cf62-11e9-8a4d-6e70bea52084.gif)

**Comment by lbalazscs** [comment] 2019-09-11 18:39
Fixed in GitHub, it will be in the next version.

**Closed by lbalazscs** 2019-09-11 18:39 UTC

**Comment by lbalazscs** [comment] 2019-09-26 16:58
This bug is fixed in Pixelitor version 4.2.1, released today.
