### ISSUE TITLE
Null error in "View->Arrange windows" options

### ISSUE THREAD

**Issue by phelieros** [lbalazscs/Pixelitor#60] opened 2019-09-26 04:28 UTC
Reproducibility: Always
Severity: Minor
Priority: Low
Software: Pixelitor 4.2.0
Windows 7 Professional 64 Bit
Java Version 1.8.0_201

Description:
Going View-Arrange windows and choosing either "Cascade" or "Tile" options throws Null error.

Steps to reproduce:
1. Go View->Arrange windows->Cascade or Go View->Arrange windows->Tile

**Comment by lbalazscs** [comment] 2019-09-26 08:55
Thank you for reporting this issue! I am closing it, because it is a duplicate of issue #43

Pixelitor 4.2.1 should be released very soon, and it will be fixed in it.

**Closed by lbalazscs** 2019-09-26 08:55 UTC
Labels: duplicate
