### ISSUE TITLE
button does not work on repeated presses

### ISSUE THREAD

**Issue by r3b3kka** [lbalazscs/Pixelitor#169] opened 2021-03-24 23:08 UTC
Summary: button does not work on repeated presses
	Severity: minor
	Priority: low
	Environment: Windows 10, Java Environment 1.8.0, Pixelitor 4.2.3
	Steps to reproduced:
	1) open picture
	2) open menu “color”
	3) “channel mixer”
	4) click twice on the button “ Convert to Black and White”
	Result:
![image](https://user-images.githubusercontent.com/81333767/112395191-81c43c00-8d30-11eb-88e0-6ee6620f65da.png)

Expected result: picture effect cancels

**Comment by lbalazscs** [comment] 2021-03-25 00:00
This is not a bug, because the effect of the "Convert to Black and White" checkbox is that the sliders are synchronized in a way that ensures that the image is always black and white, no matter how you drag them. When it's checked, they move together, when it's not checked, they can be moved freely, allowing colors.

But it's a UI design issue, it should be more clear.

**Comment by lbalazscs** [comment] 2021-03-26 00:25
I checked in a fix where I renamed the "Convert to Black and White" checkbox to "Allow only Black and White", and I also added a tooltip.

**Comment by lbalazscs** [comment] 2022-04-14 22:52
The fix is included in the final 4.3.0, which was just released.

**Closed by lbalazscs** 2022-04-14 22:52 UTC
Labels: enhancement
