### ISSUE TITLE
Using TAB for switching Show Hidden/Hide All doesen't work after 3 switching

### ISSUE THREAD

**Issue by Alexander09011988** [lbalazscs/Pixelitor#51] opened 2019-09-19 05:31 UTC
Reproducibility: Always
Severity: Minor
Priority: Medium
Software:
Pixelitor 4.2.0
Windows 10 64 Bit
Java Version 1.8.0_221

Description:
It is imposible to use TAB for switching Show Hidden/Hide All after 3 switching

Steps to reproduce:
1.Run Pixelitor
2.Press TAB >3 times

Expected Result: 
Possibility of switching Show Hidden/Hide All by press TAB

Actual Result: 
Impossible to switching Show Hidden/Hide All by press TAB

**Comment by lbalazscs** [comment] 2019-09-19 08:03
Thank you for reporting it, but I am closing this issue, because it is a duplicate of #41

**Closed by lbalazscs** 2019-09-19 08:03 UTC
