### ISSUE TITLE
On resolution 1366x768 not available icon "Set Background Color" in Tool me

### ISSUE THREAD

**Issue by Alexander09011988** [lbalazscs/Pixelitor#52] opened 2019-09-19 05:43 UTC
Reproducibility: Always
Severity: Minor
Priority: Medium
Software:
Pixelitor 4.2.0
Windows 10 64 Bit
Java Version 1.8.0_221

Description:
After Runing Pixelitor on resolution 1366x768 and full screen mode icon "Set Background Color" in Tool menu is not available

Steps to reproduce:
1.Run Pixelitor on resolution 1366x768
2.Go to full screen mode

Expected Result: 
Icon "Set Background Color" in Tool menu is available

Actual Result: 
Icon "Set Background Color" in Tool menu is not available

Attachment
![Баг](https://user-images.githubusercontent.com/55510713/65216418-ffbfdb00-dada-11e9-89c7-9d4adfeb3432.jpg)

**Comment by lbalazscs** [comment] 2019-09-19 08:06
Thank you for reporting it, but I am closing this issue, because it is a duplicate of #36

**Closed by lbalazscs** 2019-09-19 08:06 UTC
Labels: duplicate
