### ISSUE TITLE
Program error when the "Out of memory error" is received while copying a layer

### ISSUE THREAD

**Issue by fisheye123** [lbalazscs/Pixelitor#42] opened 2019-09-04 16:33 UTC
**Severity**: Minor
**Priority**: Medium
**Reproducibility**: Always
**Environment**: Pixelitor 4.2.0, Windows 10 x64, Java 1.8.0_221
**Steps to reproduce**:
1) Run the Pixelitor
2) Click on the tab "File" and select "Open" in the drop-down list
3) In the window that opens, find the path to the attached image and select it
4) Press the button "Open"
5) Press the button "Duplicates the active layers" located at the bottom of the layout elements "Layers"
6) Press the button "OK" in the "Out of memory error" window 

**Actual result**: Program error message appeared
`
Message:
    java.lang.NullPointerException
Level:
    SEVERE
Stack Trace:
null
    java.awt.image.DirectColorModel.isCompatibleRaster(Unknown Source)
    java.awt.image.BufferedImage.<init>(Unknown Source)
    pixelitor.utils.ImageUtils.copyImage(ImageUtils.java:649)
    pixelitor.layers.ImageLayer.duplicate(ImageLayer.java:245)
    pixelitor.layers.ImageLayer.duplicate(ImageLayer.java:71)
    pixelitor.Composition.duplicateActiveLayer(Composition.java:335)
    pixelitor.layers.DuplicateLayerAction.actionPerformed(DuplicateLayerAction.java:47)
    javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
    javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
    javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
    javax.swing.DefaultButtonModel.setPressed(Unknown Source)
    javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
    java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
    java.awt.Component.processMouseEvent(Unknown Source)
    javax.swing.JComponent.processMouseEvent(Unknown Source)
    java.awt.Component.processEvent(Unknown Source)
    java.awt.Container.processEvent(Unknown Source)
    java.awt.Component.dispatchEventImpl(Unknown Source)
    java.awt.Container.dispatchEventImpl(Unknown Source)
    java.awt.Component.dispatchEvent(Unknown Source)
    java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    java.awt.Container.dispatchEventImpl(Unknown Source)
    java.awt.Window.dispatchEventImpl(Unknown Source)
    java.awt.Component.dispatchEvent(Unknown Source)
    java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    java.awt.EventQueue.access$500(Unknown Source)
    java.awt.EventQueue$3.run(Unknown Source)
    java.awt.EventQueue$3.run(Unknown Source)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    java.awt.EventQueue$4.run(Unknown Source)
    java.awt.EventQueue$4.run(Unknown Source)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    java.awt.EventQueue.dispatchEvent(Unknown Source)
    java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    java.awt.EventDispatchThread.run(Unknown Source)`
**Expected result**: Program error message does not appear
**Attachments**:  15000px*5052px
![2893346171_11a4df8533_o](https://user-images.githubusercontent.com/17645129/64273833-56220b00-cf6c-11e9-9905-e3c92c1d5498.jpg)

**Comment by lbalazscs** [comment] 2019-09-04 18:57
In this case it was not necessary to attach the image, since this could be reproduced even with a 15000*5000 new  (File/New) image, only the size matters. It's not a problem, I'm just saying that you shouldn't always bother - attaching the image is important only if it couldn't be opened.
Fixed in GitHub, it will be in the next version.

**Closed by lbalazscs** 2019-09-04 18:57 UTC

**Comment by lbalazscs** [comment] 2019-09-26 16:55
This bug is fixed in Pixelitor version 4.2.1, released today.
