### ISSUE TITLE
“Input Dark” at max value leaves artifacts at the image

### ISSUE THREAD

**Issue by BeVicky** [lbalazscs/Pixelitor#88] opened 2019-10-09 09:34 UTC
**Pixelitor:** 4.2.1
**OS:** Windows 10 64 Bit
**Java Version:** 1.8.0_221

**Reproducibility:** Always
**Severity:** Minor
**Priority:** Low
**Component:** Functional

**Description:** When “Input Dark” gets the max value of 254 there are artifacts still left at the image

**Steps to reproduce:**
1.	Run Pixelitor
2.	Open new image (Ctrl+O)
3.	Open “Levels” (Color -> Levels)
4.	Enter “254” value to “Input Dark”
5.	Press "Enter"

**Expected result:** Image turns to black.
**Actual result:** Image turns to black, artifacts still left at the image (Screenshots are attached).

Original Image (https://www.lifeofpix.com/photo/275-ake0260-jj-jpg/)
![275-ake0260-jj](https://user-images.githubusercontent.com/56333921/66469593-530dc380-eab2-11e9-8d47-55ee62fab672.jpg)

Image after "Input Dark" at max value is applied (artifacts are marked with red color)

![Input Dark at 254](https://user-images.githubusercontent.com/56333921/66469619-5e60ef00-eab2-11e9-8181-c37ad0956f7c.png)

**Comment by lbalazscs** [comment] 2019-10-30 22:18
This is not a bug, because the value at which the image should be completely black is not 254, but 255 (the maximal value of a 8-bit integer). Of course one could ask, why Pixelitor doesn't allow 255 (and similarly why the "Input Light" starts at 1 and not at 0). The reason is that I was lazy to think about the somewhat tricky math at the edges... Note that there are easier ways to fill an image with black, for example press D to set the default colors, then press Alt-Backspace to fill with the foreground color.
	
But I guess I could see this as a feature request to make it work like some other image editors which allow 0 and 255 in their Levels filter.

**Comment by lbalazscs** [comment] 2019-10-31 17:57
Implemented in GitHub, it will be in the next version.

**Comment by lbalazscs** [comment] 2019-12-11 20:21
Implemented in Pixelitor version 4.2.3, released today.

**Closed by lbalazscs** 2019-12-11 20:21 UTC
Labels: enhancement
