### ISSUE TITLE
An error occurs when using a hotkey CTRL+C

### ISSUE THREAD

**Issue by a79219505050** [lbalazscs/Pixelitor#181] opened 2021-04-14 17:13 UTC
Environment: Laptop, Win 10 64 , Pixelitor 4.2.3

Steps to reproduce:
1.Open an image or create a new one
2.By holding down Ctrl, press the "C" key quickly several times (4-7)

Expected result: the error does not appear 
Actual result: there is the programm error. 
[error.txt](https://github.com/lbalazscs/Pixelitor/files/6312559/error.txt)
<img width="831" alt="1" src="https://user-images.githubusercontent.com/82383267/114751371-c22a3f00-9d5d-11eb-97ee-00403dd3eaeb.png">

Note: details in the attachment

**Comment by lbalazscs** [comment] 2021-04-14 21:08
Although I couldn't reproduce the error message, it should be fixed in the GitHub version. Probably related to https://stackoverflow.com/questions/51797673/in-java-why-do-i-get-java-lang-illegalstateexception-cannot-open-system-clipboa

**Comment by lbalazscs** [comment] 2022-04-14 22:57
The fix is included in the final 4.3.0, which was just released.

**Closed by lbalazscs** 2022-04-14 22:57 UTC
Labels: bug
